server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  gateway:
    routes:
      - id: request-service
        uri: lb://employee-request-service
        predicates:
          - Path=/requests/**
      - id: activity-service
        uri: lb://employee-activity-service
        predicates:
          - Path=/activities/**
      - id: reward-service
        uri: lb://employee-reward-service
        predicates:
          - Path=/rewards/**
      - id: profile-service
        uri: lb://employee-profile-service
        predicates:
          - Path=/profiles/**